spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_assignment
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 20 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior
      leak-detection-threshold: 20000
  servlet:
    multipart:
      max-file-size: 35MB
      file-size-threshold: 35MB
      max-request-size: 35MB
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      INDENT_OUTPUT: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true